FROM node:14.18.1-alpine as build

WORKDIR '/app'

COPY package.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

FROM nginx
COPY --from=build /app/dist /usr/share/nginx/html
